name: .NET

on:
  push:
    branches:
      - '**'        # matches every branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4
        with:
          prefix: CI_
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.x
          3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Nerdbank.GitVersioning
      id: nbgv
      uses: dotnet/nbgv@v0.4.1
    - run: |
        echo 'refname=${{ env.GITHUB_REF_SLUG }}'
        echo 'SemVer1=${{ steps.nbgv.outputs.SemVer1 }}'
        echo 'SemVer2=${{ steps.nbgv.outputs.SemVer2 }}'
        echo 'CloudBuildNumber=${{ steps.nbgv.outputs.CloudBuildNumber }}'
        echo 'SimpleVersion=${{ steps.nbgv.outputs.SimpleVersion }}'
        echo 'PrereleaseVersion=${{ steps.nbgv.outputs.PrereleaseVersion }}'
    #- name: Build
    #  run: dotnet build --configuration Release -p:Version=${{ steps.nbgv.outputs.SemVer2 }} --no-restore
    #- name: Pack
    #  run: dotnet pack --configuration Release --no-build -p:PackageVersion=${{ steps.nbgv.outputs.SemVer2 }}
    #- name: Push
    #  run: dotnet nuget push **/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/urbansportsclub/index.json --skip-duplicate --no-symbols
